FROM python:3.9

WORKDIR /opt
RUN pip install --upgrade pip
RUN pip install numpy==1.23.4 \
				pandas==1.5.1 \
				scikit-learn==1.3.0 \
				plotly==5.1.0 \
				matplotlib==3.6.2 \
				seaborn==0.12.2 \
				streamlit==1.26.0 \
				streamlit_option_menu==0.3.6

WORKDIR /work